### ISSUE TITLE
sinricpro with ESPAsyncWebServer

### ISSUE THREAD

**Issue by smartswitchsio** [sinricpro/esp8266-esp32-sdk#166] opened 2021-03-26 10:35 UTC
How to use with ESPAsyncWebServer, kindly guide me to use with this web sockets server

**Comment by kakopappa** [comment] 2021-03-26 14:59
https://techtutorialsx.com/2018/08/14/esp32-async-http-web-server-websockets-introduction/

**Comment by smartswitchsio** [comment] 2021-03-27 04:53
Thanks for the reply, i am having to trouble to connect sinricpro using ESPAsyncWebServer, Kindly give basic example to connect with ESPAsyncWebServer

**Comment by sivar2311** [comment] 2021-03-27 05:17
Hi @smartswitchsio 

There is no basic example.
Right now, the SDK works with websockets library in normal mode. Switching to AsyncWebSocket is not (yet) implemented. Maybe this will become available in future.

**Comment by sivar2311** [comment] 2021-03-27 06:00
Update: 
As long as AsyncWebsocket does not support wss / SSL, this will not be implemented in the SinricPro SDK
Please note https://github.com/Links2004/arduinoWebSockets#limitations-for-async

**Comment by sivar2311** [comment] 2021-03-28 04:52
Hi @smartswitchsio 

I had to revert my last comments.

AsyncWebServer can be used without any issues.

**Comment by smartswitchsio** [comment] 2021-03-28 05:51
please provide example to use AsyncWebServer

**Comment by sivar2311** [comment] 2021-03-28 06:04
The library is about communication with SinricPro.
You need to implement your own web server.

**Comment by sivar2311** [comment] 2021-03-28 06:51
Ok... here is an example how it could be done:

```C++

#ifdef ENABLE_DEBUG
       #define DEBUG_ESP_PORT Serial
       #define NODEBUG_WEBSOCKETS
       #define NDEBUG
#endif 

#include <Arduino.h>
#ifdef ESP8266 
       #include <ESP8266WiFi.h>
#endif 
#ifdef ESP32   
       #include <WiFi.h>
#endif
#include <ESPAsyncWebServer.h>

#include "SinricPro.h"
#include "SinricProSwitch.h"

#define WIFI_SSID         ""    
#define WIFI_PASS         ""

#define APP_KEY           ""      // Should look like "de0bxxxx-1x3x-4x3x-ax2x-5dabxxxxxxxx"
#define APP_SECRET        ""      // Should look like "5f36xxxx-x3x7-4x3x-xexe-e86724a9xxxx-4c4axxxx-3x3x-x5xe-x9x3-333d65xxxxxx"

#define SWITCH_ID         ""      // Should look like "5dc1564130xxxxxxxxxxxxxx"
#define SWITCH_PIN        LED_BUILTIN   

#define BAUD_RATE         115200                // Change baudrate to your need

SinricProSwitch &mySwitch = SinricPro[SWITCH_ID];
AsyncWebServer server(80);

bool myPowerState = false;

bool onPowerState(const String &deviceId, bool &state) {
  Serial.printf("Device %s turned %s (via SinricPro) \r\n", deviceId.c_str(), state?"on":"off");
  myPowerState = state;
  digitalWrite(SWITCH_PIN, myPowerState?LOW:HIGH);
  return true; // request handled properly
}

void webinterface(AsyncWebServerRequest *request) {
  if (!request->hasParam("state")) {
    String currentStateStr = myPowerState ? "on" : "off";
    String response = "<html><body>Switch is " + currentStateStr + " (<a href=\"/" SWITCH_ID "?state=on\">on</a> <a href=\"/" SWITCH_ID "?state=off\">off</a> <a href=\"/" SWITCH_ID "?state=flip\">flip</a>)</body></html>";
    request->send(200, "text/html", response);
  } else {
    AsyncWebParameter* param = request->getParam("state");
    bool newState;
    if (param->value() == "on") newState = true;
    if (param->value() == "off") newState = false;
    if (param->value() == "flip") newState = !myPowerState;
    if (newState != myPowerState) mySwitch.sendPowerStateEvent(myPowerState);
    myPowerState = newState;
    digitalWrite(SWITCH_PIN, myPowerState);
    request->redirect("/" SWITCH_ID);
  }
}

// setup function for WiFi connection
void setupWiFi() {
  Serial.printf("\r\n[Wifi]: Connecting");
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  while (!WiFi.isConnected()) { Serial.printf("."); delay(100); };
  Serial.printf("connected!\r\n[WiFi]: IP-Address is %s\r\n", WiFi.localIP().toString().c_str());
}

// setup function for SinricPro
void setupSinricPro() {
  mySwitch.onPowerState(onPowerState);

  SinricPro.onConnected([](){ Serial.printf("Connected to SinricPro\r\n"); }); 
  SinricPro.onDisconnected([](){ Serial.printf("Disconnected from SinricPro\r\n"); });
  SinricPro.begin(APP_KEY, APP_SECRET);
}

void setupWebServer() {
  server.on("/" SWITCH_ID, HTTP_GET, webinterface);
  server.begin();
  Serial.printf("Open you web browser and navigate to http://%s/%s\r\n", WiFi.localIP().toString().c_str(), SWITCH_ID);
}

// main setup function
void setup() {
  pinMode(SWITCH_PIN, OUTPUT); // define LED GPIO as output

  Serial.begin(BAUD_RATE); Serial.printf("\r\n\r\n");
  setupWiFi();
  setupSinricPro();
  setupWebServer();
}

void loop() {
  SinricPro.handle();
}
```

I think, this should give you a good starting point.

**Comment by smartswitchsio** [comment] 2021-03-31 15:51
HI bro, Thanks for your example code.

**Comment by smartswitchsio** [comment] 2021-04-13 15:19
This above given example using two different websockets library, kindly give example only with AsyncWebSocket library.

**Comment by sivar2311** [comment] 2021-04-13 15:24
Sorry, the SDK is fixed to ArduinoWebsockets... 

So it is not possible to use another one, except to rewrite the complete sdk.

**Comment by sivar2311** [comment] 2021-04-13 15:41
But it should be possible to use any websockets you want to use, regardless which one is used ineternally in the sdk.

**Comment by smartswitchsio** [comment] 2021-04-13 15:48
Please give simple switch example only with AsyncWebSocket library

**Comment by sivar2311** [comment] 2021-04-13 15:59
I cant give you, because i dont have one.
2 questions:
1. Do you want to use SinricPro without this library? 
2. What is your intention in using AsyncWebsockets?

**Comment by smartswitchsio** [comment] 2021-04-13 16:05
I am using ESP8266 with  AsyncWebsockets library to on/off relay with custom features. if i use SinricPro library with my program web page not loading. it's rebooting the device

**Comment by sivar2311** [comment] 2021-04-13 16:19
If AsyncWebserver is running without issues, i cannot see why AsyncWebsocket is not. 

Did you do any debugging to find out what is causing the crash?

**Comment by smartswitchsio** [comment] 2021-04-13 16:36
This is the below error getting

ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x4010f000, len 3584, room 16 
tail 0
chksum 0xb0
csum 0xb0
v2843a5ac
~ld

**Comment by sivar2311** [comment] 2021-04-13 16:53
This is a boot message... not an error message and no debug information.
The only reason i can see is the reboot reason "watchdog" (wdt).
So, this is going to be completeley off-topic (original topic was about ESPAsyncWebserver).

Please do the 4 following steps:
1. Close this issue because AsyncWebserver issue was solved...see my post [above](https://github.com/sinricpro/esp8266-esp32-sdk/issues/166#issuecomment-808856420)
2. Open a new issue
3. Share your code (create a git repository or use gist.github.com) so I will be ble to reproduce the error you have
4. Provide detailed informations (debug logs etc etc.)

**Closed** 2021-04-16 10:16 UTC
