### ISSUE TITLE
Error Compiling Board

### ISSUE THREAD

**Issue by JrPaul6** [sinricpro/esp8266-esp32-sdk#227] opened 2021-10-29 18:02 UTC
I'm trying to compile the code in "Lock" examples of SinricPro library but I get an error while compiling which is "Error compiling board ****". I tried the both boards Generic ESP8266 Module, and NodeMCU 1.0 (ESP 12-E Module) nut none of them fixed the error. Is there any solution please?
Note: I modified the credentials i.e. Device ID, App Key, and App Secret based on mine on SinricPro.

**Comment by sivar2311** [comment] 2021-10-29 18:06
Which board do you use?

Can another (non SinricPro related) sketch be compiled without this error?
I suppose that something may be wrong with your Arduino installation.

**Comment by JrPaul6** [comment] 2021-10-29 18:13
I'm using nodemcu v3 12-e board.
Yes it compiles other sketches not related to Sinric Pro, but the problem persists only when compiling this example.

**Comment by sivar2311** [comment] 2021-10-29 18:14
Please post the complete error message.

**Comment by JrPaul6** [comment] 2021-10-29 18:18
Arduino: 1.8.16 (Windows Store 1.8.51.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"





















In file included from C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:35,

                 from C:\Users\hasaw\OneDrive\سطح المكتب\Lock\Lock.ino:31:

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricProInterface.h:42:11: error: JsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

   42 |     virtual void sendMessage(JsonDocument& jsonEvent);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                           

In file included from C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:35,

                 from C:\Users\hasaw\OneDrive\سطح المكتب\Lock\Lock.ino:31:

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricProInterface.h:43:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

   43 |     virtual DynamicJsonDocument prepareEvent(DeviceId deviceId, const char* action, const char* cause);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                 

In file included from C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:36,

                 from C:\Users\hasaw\OneDrive\سطح المكتب\Lock\Lock.ino:31:

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricProDeviceInterface.h:50:11: error: JsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

   50 |     virtual bool sendEvent(JsonDocument& event) = 0;

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                             

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricProDeviceInterface.h:51:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

   51 |     virtual DynamicJsonDocument prepareEvent(const DeviceId &deviceId, const char* action, const char* cause) = 0;

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                      

In file included from C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:39,

                 from C:\Users\hasaw\OneDrive\سطح المكتب\Lock\Lock.ino:31:

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricProSignature.h:38:11: error: JsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

   38 | String calculateSignature(const char* key, JsonDocument &jsonMessage)

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                            

In file included from C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:39,

                 from C:\Users\hasaw\OneDrive\سطح المكتب\Lock\Lock.ino:31:

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricProSignature.h:43:11: error: serializeJson is a function from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

   43 |   String jsonPayload; serializeJson(jsonMessage["payload"], jsonPayload);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                            

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricProSignature.h:61:11: error: JsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

   61 | bool verifyMessage(String key, JsonDocument &jsonMessage)

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                        

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricProSignature.h:68:11: error: JsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

   68 | String signMessage(String key, JsonDocument &jsonMessage)

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                        

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricProSignature.h:75:11: error: serializeJson is a function from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

   75 |   serializeJson(jsonMessage, signedMessageString);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                   

In file included from C:\Users\hasaw\OneDrive\سطح المكتب\Lock\Lock.ino:31:

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:91:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

   91 |     DynamicJsonDocument prepareResponse(JsonDocument& requestMessage);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                  

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:91:11: error: JsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

   91 |     DynamicJsonDocument prepareResponse(JsonDocument& requestMessage);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                           

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:92:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

   92 |     DynamicJsonDocument prepareEvent(DeviceId deviceId, const char* action, const char* cause) override;

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:93:11: error: JsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

   93 |     void sendMessage(JsonDocument& jsonMessage) override;

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                        

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:152:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  152 |     void handleRequest(DynamicJsonDocument& requestMessage, interface_t Interface);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                     

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:153:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  153 |     void handleResponse(DynamicJsonDocument& responseMessage);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                          

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:155:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  155 |     DynamicJsonDocument prepareRequest(DeviceId deviceId, const char* action);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                          

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:171:11: error: JsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  171 |     void extractTimestamp(JsonDocument &message);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:399:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  399 | DynamicJsonDocument SinricProClass::prepareRequest(DeviceId deviceId, const char* action)

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                               

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:401:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  401 |   DynamicJsonDocument requestMessage(1024);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                             

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:418:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  418 | void SinricProClass::handleResponse(DynamicJsonDocument& responseMessage)

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                               

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:423:11: error: serializeJsonPretty is a function from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  423 |   serializeJsonPretty(responseMessage, SRP_DEBUG_OUTPUT);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                  

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:428:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  428 | void SinricProClass::handleRequest(DynamicJsonDocument& requestMessage, interface_t Interface)

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                          

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:433:11: error: serializeJsonPretty is a function from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  433 |   serializeJsonPretty(requestMessage, SRP_DEBUG_OUTPUT);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                   

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:437:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  437 |   DynamicJsonDocument responseMessage = prepareResponse(requestMessage);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:469:11: error: serializeJson is a function from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  469 |   serializeJson(responseMessage, responseString);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                    

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:485:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  485 |     DynamicJsonDocument jsonMessage(1024);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                              

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:486:11: error: deserializeJson is a function from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  486 |     deserializeJson(jsonMessage, rawMessage->getMessage());

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                            

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:537:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  537 |     DynamicJsonDocument jsonMessage(1024);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                              

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:538:11: error: deserializeJson is a function from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  538 |     deserializeJson(jsonMessage, rawMessage->getMessage());

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                            

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:545:11: error: serializeJson is a function from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  545 |     serializeJson(jsonMessage, messageStr);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                          

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:548:11: error: serializeJsonPretty is a function from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  548 |     serializeJsonPretty(jsonMessage, SRP_DEBUG_OUTPUT);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                    

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:656:11: error: JsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  656 | void SinricProClass::extractTimestamp(JsonDocument &message)

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                     

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:684:11: error: JsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  684 | void SinricProClass::sendMessage(JsonDocument& jsonMessage)

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                      

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:697:11: error: serializeJson is a function from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  697 |   serializeJson(jsonMessage, messageString);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                         

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:715:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  715 | DynamicJsonDocument SinricProClass::prepareResponse(JsonDocument& requestMessage)

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                       

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:715:11: error: JsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  715 | DynamicJsonDocument SinricProClass::prepareResponse(JsonDocument& requestMessage)

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:717:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  717 |   DynamicJsonDocument responseMessage(1024);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                            

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:739:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  739 | DynamicJsonDocument SinricProClass::prepareEvent(DeviceId deviceId, const char* action, const char* cause)

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                              

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricPro.h:741:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  741 |   DynamicJsonDocument eventMessage(1024);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                               

In file included from C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricProLock.h:35,

                 from C:\Users\hasaw\OneDrive\سطح المكتب\Lock\Lock.ino:32:

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricProDevice.h:85:11: error: JsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

   85 |     virtual bool sendEvent(JsonDocument& event);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                 

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricProDevice.h:86:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

   86 |     virtual DynamicJsonDocument prepareEvent(const DeviceId &deviceId, const char* action, const char* cause);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                          

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricProDevice.h:139:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  139 | DynamicJsonDocument SinricProDevice::prepareEvent(const DeviceId &deviceId, const char* action, const char* cause)

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                      

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricProDevice.h:146:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  146 |   return DynamicJsonDocument(1024);

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                     

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricProDevice.h:150:11: error: JsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  150 | bool SinricProDevice::sendEvent(JsonDocument& event)

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                             

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricProDevice.h:230:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  230 |   DynamicJsonDocument eventMessage = prepareEvent(deviceId, "setPowerState", cause.c_str());

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                            

In file included from C:\Users\hasaw\OneDrive\سطح المكتب\Lock\Lock.ino:32:

C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic\src/SinricProLock.h:138:11: error: DynamicJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.

  138 |   DynamicJsonDocument eventMessage = prepareEvent(deviceId, "setLockState", cause.c_str());

      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                             

Multiple libraries were found for "SinricPro.h"

 Used: C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\SinricPro_Generic

 Not used: C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\esp8266-esp32-sdk-master

Multiple libraries were found for "ArduinoJson.h"

 Used: C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\ArduinoJson

 Not used: C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\ArduinoJson-6.18.5

 Not used: C:\Users\hasaw\OneDrive\Documents\Arduino\libraries\ArduinoJson-6.x

exit status 1

Error compiling for board NodeMCU 1.0 (ESP-12E Module).



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by sivar2311** [comment] 2021-10-29 18:25
The issue is with this:
**Multiple libraries were found for "SinricPro.h"**
**Multiple libraries were found for "ArduinoJson.h"**

Looks like you are using 3rd party library **SinricPro_Generic** (not the official one provided in this repository).

Uninstall SinricPro Generic and install **SinricPro 2.9.10**
Also make sure only one Version of ArduinoJson is installed

**Comment by JrPaul6** [comment] 2021-10-29 18:40
It works now
Thanks a lot

**Comment by sivar2311** [comment] 2021-10-29 18:44
Your're welcome!

Please close this issue if there are no further questions on this topic.

**Closed** 2021-10-29 21:10 UTC
